Update README.md
HealthITAU/pyconnectwise pull request #7
Opened 2023-07-25 02:00 UTC by pedro-101

Replaced non coding references to ConnectWise Automate with Labtech.

2023-07-25 22:14 UTC, chrisdeke requested changes
42: This is incorrect, it should either be Connectwise Automate or Labtech not just "Connectwise"
74: This will break the code example?

2023-07-26 23:41 UTC, Yoshify requested changes
Couple changes to make, then we can merge.

2023-07-26 23:41 UTC, Yoshify commented on README.md
> +  - [ConnectWise ](#connectwise-)
This breaks the hyper link to line 72

2023-07-26 23:41 UTC, Yoshify commented on README.md
> +_api_client = ConnectWiseAPIClient(
Lets keep the code example as is with automate_api_client

2023-07-26 23:41 UTC, Yoshify commented on README.md
> +# pyConnectWise - An API library for ConnectWise Manage and Labtech (ConnectWise Automate), written in Python
I'm more inclined to reversing this and having it be ConnectWise Automate (Labtech) as having the current name (former name) makes more sense.

2023-07-26 23:41 UTC, Yoshify commented on README.md
> +pyConnectWise currently supports both ConnectWise Manage and Labtech (ConnectWise Automate).
See review for line 3.

2023-08-03 21:55 UTC, closed without merging